"""Updated models to handle errors

Revision ID: 97f604e529fa
Revises: 57881204f4e6
Create Date: 2024-03-10 08:37:37.752923

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97f604e529fa'
down_revision = '57881204f4e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
